// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Classifies rice grains (long, short, broken) based on an image.
 *
 * - classifyRice - A function that handles the rice classification process.
 * - ClassifyRiceInput - The input type for the classifyRice function.
 * - ClassifyRiceOutput - The return type for the classifyRice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ClassifyRiceInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of rice grains, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ClassifyRiceInput = z.infer<typeof ClassifyRiceInputSchema>;

const ClassifyRiceOutputSchema = z.object({
  classification: z
    .enum(['long grain', 'short grain', 'broken'])
    .describe('The classification of the rice grains.'),
  confidence: z
    .number()
    .describe('The confidence level of the classification (0-1).'),
});
export type ClassifyRiceOutput = z.infer<typeof ClassifyRiceOutputSchema>;

export async function classifyRice(input: ClassifyRiceInput): Promise<ClassifyRiceOutput> {
  return classifyRiceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'classifyRicePrompt',
  input: {schema: ClassifyRiceInputSchema},
  output: {schema: ClassifyRiceOutputSchema},
  prompt: `You are an expert in rice grain classification.

  Analyze the image and classify the rice grains as either 'long grain', 'short grain', or 'broken'.
  Also, provide a confidence level for your classification between 0 and 1.

  Image: {{media url=photoDataUri}}
  `,
});

const classifyRiceFlow = ai.defineFlow(
  {
    name: 'classifyRiceFlow',
    inputSchema: ClassifyRiceInputSchema,
    outputSchema: ClassifyRiceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
